[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="ctx" type="info.magnolia.context.MgnlContext" --]
[#-- @ftlvariable name="cmsfn" type="info.magnolia.templating.functions.TemplatingFunctions" --]
[#-- @ftlvariable name="tourfn" type="org.packrunners.webapp.courses.TourTemplatingFunctions" --]
